 /*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.CodeGeneration.CodeGeneration;
import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Lexer.Symbols.EndOfInputType;
import compiler.Parser.CFG.ASTNode;
import compiler.Parser.CFG.ASTPrinter;
import compiler.Parser.CFG.ProgramNode;
import compiler.Parser.Parser;
import compiler.Semantic.Semantic;

import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Objects;

public class Compiler {
    public static void main(String[] args) throws IOException {
        /*
        if(Objects.equals(args[0], "-lexer")){
            String input = args[1];
            try {
                Path filePath = Paths.get(input);
                String content = Files.readString(filePath);
                Lexer lexer = new Lexer(new StringReader(content));
                Symbol currentSymbol;
                do{
                    currentSymbol = lexer.getNextSymbol();
                    System.out.println(currentSymbol);
                }while(currentSymbol.getClass() != EndOfInputType.class);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        else if(Objects.equals(args[0], "-parser")){
            String input = args[1];
            Path filePath = Paths.get(input);
            String content = Files.readString(filePath);
            Lexer lexer = new Lexer(new StringReader(content));
            Parser parser = new Parser(lexer);
            ASTNode ast = parser.getAST();
            ASTPrinter.print(ast);
        }
        else{
            String input = args[0];
            Path filePath = Paths.get(input);
            String content = Files.readString(filePath);
            Lexer lexer = new Lexer(new StringReader(content));
            Parser parser = new Parser(lexer);
            ASTNode ast = parser.getAST();
            //ASTPrinter.print(ast);
            Semantic sem = new Semantic((ProgramNode) ast);
            sem.findSemanticErrors();
        }
        //return 0;
         */
        String input = args[0];
        Path filePath = Paths.get(input);
        String content = Files.readString(filePath);
        Lexer lexer = new Lexer(new StringReader(content));
        Parser parser = new Parser(lexer);
        ASTNode ast = parser.getAST();
        Semantic sem = new Semantic((ProgramNode) ast);
        sem.findSemanticErrors();
        String pathToClassFiles = null;
        if (args.length > 1) {
            pathToClassFiles = args[2];
        }
        CodeGeneration cg = new CodeGeneration((ProgramNode) ast, pathToClassFiles);
        cg.codeGeneration();
    }
}
