 /*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Lexer.Symbols.EndOfInputType;
import compiler.Parser.CFG.ASTNode;
import compiler.Parser.CFG.ASTPrinter;
import compiler.Parser.Parser;

import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Objects;

public class Compiler {
    public static void main(String[] args) throws IOException {
        if(Objects.equals(args[0], "-lexer")){
            String input = args[1];
            try {
                Path filePath = Paths.get(input);
                String content = Files.readString(filePath);
                Lexer lexer = new Lexer(new StringReader(content));
                Symbol currentSymbol;
                do{
                    currentSymbol = lexer.getNextSymbol();
                    System.out.println(currentSymbol);
                }while(currentSymbol.getClass() != EndOfInputType.class);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        else if(Objects.equals(args[0], "-parser")){
            String input = args[1];
            Path filePath = Paths.get(input);
            String content = Files.readString(filePath);
            Lexer lexer = new Lexer(new StringReader(content));
            Parser parser = new Parser(lexer);
            ASTNode ast = parser.getAST();
            ASTPrinter.print(ast);
        }
        //return 0;
    }
}
